database:
  kind: sqlite
  path: ${SQLITE_PATH:-/tmp/demo_tezos_head.sqlite}

sentry:
  dsn: ${SENTRY_DSN:-''}
  environment: ${SENTRY_ENVIRONMENT:-''}

prometheus:
  host: 0.0.0.0

api:
  host: 0.0.0.0