name: demo_blank

services:
  dipdup:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: ["-C", "sqlite", "run"]
    restart: always
    env_file: .env
    ports:
      - 46339
      - 9000
    volumes:
      - sqlite:${SQLITE_PATH:-/tmp/demo_blank.sqlite}

volumes:
  sqlite: