# generated by DipDup 8.2.0rc1

from __future__ import annotations

from typing import TypedDict

"""
Some assets were transferred.
"""
V700 = TypedDict(
    'V700',
    {
        'asset_id': int,
        'from': str,
        'to': str,
        'amount': int,
    },
)
